/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#141313',
        'surface-dim': '#141313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2b2a2a',
        'surface-container-highest': '#353434',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c8c5ca',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#919095',
        'outline-variant': '#47464a',
        'surface-tint': '#c8c6c8',
        primary: '#c8c6c8',
        'on-primary': '#313032',
        'primary-container': '#09090b',
        'on-primary-container': '#7a787b',
        'inverse-primary': '#5f5e60',
        secondary: '#adc6ff',
        'on-secondary': '#002e6a',
        'secondary-container': '#0566d9',
        'on-secondary-container': '#e6ecff',
        tertiary: '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#000c05',
        'on-tertiary-container': '#008a5f',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#141313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353434',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
